# Generated by Django 5.2 on 2026-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'student'), ('student_id__isnull', False), models.Q(('student_id', ''), _negated=True), ('staff_id__isnull', True)), models.Q(('role', 'lecturer'), ('staff_id__isnull', False), models.Q(('staff_id', ''), _negated=True), ('student_id__isnull', True)), models.Q(('role', 'admin'), ('student_id__isnull', True), ('staff_id__isnull', True)), _connector='OR'), name='users_role_ids_valid'),
        ),
    ]
