# Generated by Django 5.2 on 2026-02-25 03:47

from django.db import migrations, models


def normalize_user_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        role = (user.role or '').strip()
        if role:
            continue

        if user.is_superuser or user.is_staff:
            user.role = 'admin'
            user.student_id = None
            user.staff_id = None
        elif user.staff_id:
            user.role = 'lecturer'
            user.student_id = None
        elif user.student_id:
            user.role = 'student'
            user.staff_id = None
        else:
            user.role = 'student'
            user.student_id = f"L{user.pk}"
            user.staff_id = None

        user.save(update_fields=['role', 'student_id', 'staff_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RunPython(normalize_user_roles, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'student'), ('student_id__isnull', False), models.Q(('student_id', ''), _negated=True), ('staff_id__isnull', True)), models.Q(('role', 'lecturer'), ('staff_id__isnull', False), models.Q(('staff_id', ''), _negated=True), ('student_id__isnull', True)), models.Q(('role', 'admin'), ('student_id__isnull', True), ('staff_id__isnull', True)), _connector='OR'), name='users_role_ids_valid'),
        ),
    ]
